-- Drop the IDENTITY constraint first
ALTER TABLE "megadata_token" ALTER COLUMN "row_id" DROP IDENTITY IF EXISTS;

-- Drop the default if it exists
ALTER TABLE "megadata_token" ALTER COLUMN "row_id" DROP DEFAULT;

-- Add GENERATED BY DEFAULT and restart the sequence from the max value
ALTER TABLE "megadata_token" ALTER COLUMN "row_id" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('megadata_token', 'row_id'), (SELECT MAX(row_id) FROM megadata_token)); 